// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SustenAI.DataBase;

#nullable disable

namespace SustenAI.Migrations
{
    [DbContext(typeof(SustenAIDBContext))]
    [Migration("20240916182941_InitialDB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SustenAI.Models.Arquivo", b =>
                {
                    b.Property<int>("IdArq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_arq");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArq"));

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_upload");

                    b.Property<string>("NomeArq")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome_arq");

                    b.Property<string>("TipoArq")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("tipo_arq");

                    b.HasKey("IdArq");

                    b.ToTable("sustenAI_arquivos", (string)null);
                });

            modelBuilder.Entity("SustenAI.Models.Previsao", b =>
                {
                    b.Property<int>("IdPrev")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_prev");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrev"));

                    b.Property<DateTime>("DataHoraPrev")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_hora_prev");

                    b.Property<int>("IdProd")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_prod");

                    b.Property<decimal>("PrecisaoPrev")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("precisao_prev");

                    b.Property<DateTime>("UltimaAtt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ultima_att");

                    b.HasKey("IdPrev");

                    b.ToTable("sustenAI_previsoes", (string)null);
                });

            modelBuilder.Entity("SustenAI.Models.Produto", b =>
                {
                    b.Property<int>("IdProd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_prod");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProd"));

                    b.Property<string>("Avaliacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("avaliacao");

                    b.Property<DateTime>("DataAtual")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_atual");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_criacao");

                    b.Property<string>("NomeProd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome_prod");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("origem");

                    b.Property<decimal>("Preco")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("preco");

                    b.Property<DateTime>("UltimaAtt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ultima_att");

                    b.HasKey("IdProd");

                    b.ToTable("susten_produtos", (string)null);
                });

            modelBuilder.Entity("SustenAI.Models.Usuario", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_user");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("email");

                    b.Property<string>("NomeEmp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome_emp");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("senha");

                    b.HasKey("IdUser");

                    b.ToTable("sustenAI_usuarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
